system:
  listen: :8888
file:
  download:
    recommend:
      info:
        path: ./static/download/recommend.doc
        name: 长三角区域教育评价变革协作联盟专家库成员推荐汇总表.doc
database:
  name: expert
  connection: mongodb://202.120.39.3:27017